### ISSUE TITLE
ParallelExecutor race condition

### ISSUE THREAD

**Issue by TIPConsulting** [Melodi17/Q-Limits#1]
`tasks[i++] = Task.Run(`

Is a race condition that could result in some tasks being abandoned. Prefer `interlocked.increment(ref i)` 

Note: the increment behavior mimics ++i, not i++, so also change the starting index to compensate

**Comment by Melodi17** [comment]
I have trouble understanding and implementing this kind of threading, are you able to give me a larger example/sample or help me implement it?

**Comment by Melodi17** [comment]
Resolved in version 2.0.6
